### ISSUE TITLE
make make

### ISSUE THREAD

**Issue by JAremko** [DeForce/LalkaChat#120]
Plz can I haz:
1. git clone https://github.com/DeForce/LalkaChat.git
2. cd LalkaChat
3. ./configure
4. make
5. make install
6. profit!

instead of:
1. git clone https://github.com/DeForce/LalkaChat.git
2. ...
3. ...
4. ...
5. ???
6. ...
7. !!!!!
8. ...
9. FUUU!

THX! :heart: 

TODO:
- [ ] JUST DO IT!

**Comment by DeForce** [comment]
I know. It's in plans. Will try to do it. It's hard for linux. 

if you can help, you can do it youself! It's kinda hard and we don't native fallback on linux to GTK

**Comment by drewoko** [comment]
mac version also plzzz

**Comment by JAremko** [comment]
> I know. It's in plans. Will try to do it. It's hard for linux.
if you can help, you can do it youself! It's kinda hard and we don't native fallback on linux to GTK

can we haz than `sudo curl -fsSL https://raw.githubusercontent.com/DeForce/LalkaChat/master/install.sh | sh` ?

**Comment by DeForce** [comment]
sudo curl -fsSL https://raw.githubusercontent.com/DeForce/LalkaChat/master/install.sh | sh

NEVER, IT'S NOT SECURE

**Comment by JAremko** [comment]
@DeForce What iz life?
![https://66.media.tumblr.com/avatar_93f1ae2c58ae_128.png](https://66.media.tumblr.com/avatar_93f1ae2c58ae_128.png)

**Comment by DeForce** [comment]
setup.py
