### ISSUE TITLE
Highlight message by filter

### ISSUE THREAD

**Issue by Djekke** [DeForce/LalkaChat#145]
Check how to highlight messages by:
- nickname (chechbox for nickname=channelname (default))
- custom filter (regexp)

**Comment by DeForce** [comment]
Nickname is already being monitored.
I will add checkbox for marking PM's to channel owner.

Custom filter by regex. 
You wan't to mark message if it passes regex?

**Comment by DeForce** [comment]
Added checkboxes for each stream portal.

Ability to mention custom nickname is in Mentions Module.
