### ISSUE TITLE
Necessary js files are not bundled

### ISSUE THREAD

**Issue by mokrinsky** [DeForce/LalkaChat#187]
In html template you use these files:

```
        <script src="js/purify.min.js"></script>
        <script src="js/vue.min.js"></script>
```

However, they're not included in both master and develop branches, so we need to manually download them.

**Comment by DeForce** [comment]
Won't be bundled in source code. 
I will add npm package json for dependancies.

**Comment by DeForce** [comment]
{
  "dependencies": {
    "dompurify": "^0.8.4",
    "vue": "^2.0.8"
  },
  "name": "lalkachat-default-theme",
  "version": "1.0.0",
  "description": "default lalkachat theme based on vue.js",
  "main": "app.js",
  "devDependencies": {}
}
done

npm package.json?

**Comment by DeForce** [comment]
Now to write script to control them all

**Comment by DeForce** [comment]
Now works after #222
