### ISSUE TITLE
Fix rendering of emotes that have special symbols

### ISSUE THREAD

**Issue by DeForce** [DeForce/LalkaChat#371]
http://i.imgur.com/g58Xc8L.png

Sent like this:
{'emote_id': u'&gt;_&lt;', 'emote_url': 'http://edge.sf.hitbox.tv/static/img/chat/default/x1.png'}
{'emote_id': u':OO', 'emote_url': 'http://edge.sf.hitbox.tv/static/img/chat/default/surprised4.png'}

**Comment by ichursin** [comment]
I have some minor suggestions.
First of all, could you use instead of emote_id, emote_url just id, url names of emote fields?
Another one, could you return emote id with open (:emote;) an close (:) tag, like this :emote;>_<:?

**Comment by DeForce** [comment]
Suggestions are implemented, already in develop. Merged as part of #434

**Comment by DeForce** [comment]
#447
