### ISSUE TITLE
Проблемы с размерами окна при смене настроек

### ISSUE THREAD

**Issue by Usernm0** [DeForce/LalkaChat#390]
Если отжать галку - показыать окно браузера, перезапустить чат, а потом выставить ее снова и опять перезапустить чат, то он перезапустится без адаптации окна под браузерную часть окна. 

Если при этом еще и оключать вместе с браузером рамки окна, то размер окна будет еще меньше и даже счетчиков не будет видно.

**Comment by DeForce** [comment]
Попробую поправить к следующему релизу.

**Comment by DeForce** [comment]
Исправлено.

Теперь чат без браузера будет "сжиматся" до минимального состояния.
Чат с браузером будет хранить последний размер когда его запускали с браузером.
