### ISSUE TITLE
Не запоминает срок жизни сообщения в вебчате

### ISSUE THREAD

**Issue by Usernm0** [DeForce/LalkaChat#392]
Собственно сабж. Стоит -1, выставляю 20 секунд, после перезапуска сбрасывается на -1.

**Comment by DeForce** [comment]
Ты используешь один и тот же стиль для gui и web'а?
В этом скорее всего проблема. 
Если используется один и тот же стиль, то сохраняются последние настройки. Скорее всего я позже это пофикшу, но пока советую использовать _gui стиль для gui, что бы были разные настройки.

**Comment by DeForce** [comment]
Пофикшено в новом релизе
