### ISSUE TITLE
Wrong message display

### ISSUE THREAD

**Issue by mokrinsky** [DeForce/LalkaChat#44]
I sent this message to chat;

> я боюсь, сейчас czt и за пять евро не пускает :)

But instead of replacing :) with emoticon, it was displayed some strange way:

![357130](https://cloud.githubusercontent.com/assets/463907/19025305/6e15e7b6-8917-11e6-908b-dd8d4f1dce1b.png)

Another one message by another user:

> доводы не убедительны что то =\

Was displayed this way:

> доводы не убедительны что то =undefined

**Comment by DeForce** [comment]
Relates to "cloud2butt" module that replaced czt with lalka, but didn't move indexes of twitch emotes.

**Comment by DeForce** [comment]
#48 Fixed c2b module
