### ISSUE TITLE
Is it possible to start without GUI?

### ISSUE THREAD

**Issue by BondarenkoArtur** [DeForce/LalkaChat#45]
For example, we configured everything in .cfg files and we don't need to have one more window of chat, only chat for stream on http server. Is it possible to make something like argument for start and start chat without gui completely in console?

**Comment by DeForce** [comment]
Yes, it is possible. GUI is a module.
Change in config.cfg: gui = True to False

**Comment by DeForce** [comment]
Closed with #49 

My bad, gui wanted different config item. Not gui, but enabled.

If you want it now before new release, change gui to enabled, and set:
enabled = False
