### ISSUE TITLE
Warn about new version

### ISSUE THREAD

**Issue by DeForce** [DeForce/LalkaChat#53]
Need to notify new users about new versions... Right now now sure how can I do that.

**Comment by BondarenkoArtur** [comment]
I've seen that livestreamer-gui grabs from github changelog and new version
Probably it was implemented [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/837ff5a963580b2dcba5e31db14a9b88a6e6d5a4/src/app/services/VersioncheckService.js)
