### ISSUE TITLE
Fallback to native web browser

### ISSUE THREAD

**Issue by DeForce** [DeForce/LalkaChat#58]
If os doesn't have chromium installed (mac, linux) fallback to native implementation

**Comment by BondarenkoArtur** [comment]
There is no cefpython in pip (probably) for linux
```
uabart@laptop > pip2 install cefpython
Collecting cefpython
Could not find a version that satisfies the requirement cefpython (from versions: )
No matching distribution found for cefpython
```

I've installed cefpython3 from [here](https://github.com/cztomczak/cefpython/wiki/Download_CEF3_Linux)
(Version: `Chromium 53.0.2785.116`)
But anyway it's doesn't works, i do have crash at start
```
> INFO:main:Loading GUI Interface
INFO:chat_gui:Application is on top
The program 'main.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 119 error_code 3 request_code 1 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

With `html2` all works fine.

**Comment by DeForce** [comment]
https://pypi.python.org/pypi/cefpython3/ doesn't have native linux binaries. 
Only for mac and windows.

For linux: https://github.com/cztomczak/cefpython/wiki/Download_CEF3_Linux
Although seems like too many work to do without make-file.
You are right.

So we need to update setup.py and gui.py to not even import cefpython if it is linux...

**Comment by BondarenkoArtur** [comment]
I didn't tried it on cefpython, but I found that in html2 version scrolling doesn't works. Is it the same on cefpython?

**Comment by DeForce** [comment]
Yes, it's by "design".

I do think that scrolling shouldn't work.
Maybe should be moved to parameter... Although there will be scrolling bars which I don't like.

**Comment by BondarenkoArtur** [comment]
Ok, fine :+1:
